import { wrapper } from 'app/store';
import { selectProfile } from 'app/store/slices/profile';
import type { NextPage } from 'next';
import Head from 'next/head';
import Link from 'next/link';
import { useSelector } from 'react-redux';

const Profile: NextPage = (props: any) => {
  const profile = useSelector(selectProfile) as any;

  return (
    <div className="container">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="row">
        <h1 className="text-center">
          Your <a href="https://featuringcode.com">Featuring Code</a>, {profile?.name}
        </h1>
        <p>
          Go to <Link href="/">
            <a>Home page</a>
          </Link>
        </p>

        <p>
          Hello, {props.profileData}!
        </p>
      </main>
    </div>
  );
};

export const getServerSideProps = wrapper.getServerSideProps(store => async ({ query }) => {
  console.log('store state', store.getState());
  const profileData = query.data || 'profile data';
  //  http://localhost:3000/profile?data='some-data'

  return {
    props: {
      profileData
    }
  };
});

export default Profile;
