import type { NextPage } from 'next';
import Head from 'next/head';
import Link from 'next/link';

const Profile: NextPage = (props: any) => {
  return (
    <div className="container">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="row">
        <h1 className="text-center">
          Your <a href="https://featuringcode.com">Featuring Code</a> Profile
        </h1>
        <p>
          Go to <Link href="/">
            <a>Home page</a>
          </Link>
        </p>

        <p>
          Hello, {props.profileData}!
        </p>
      </main>
    </div>
  );
};

export async function getServerSideProps(context: any) {
  const profileData = context.query.data || 'profile data';
  //  http://localhost:3000?data='some-data'

  return {
    props: {
      profileData
    } // will be passed to the page component as props
  };
}

export default Profile;
